Repository u-lab/rebuilt, pull requests merged in 2020-03, with the labels that each got.

#47 作品一覧概形
  assets/img/usericon-ex.jpg
  pages/users/lists/storages.vue
Labels: enhancement

#51 一般公開(/pages/:user)を一部作成
  assets/img/page_background_example.png
  assets/sass/app.scss
  assets/sass/default/navbar.scss
  assets/sass/pages/_tab_box.scss
  assets/sass/pages/_user_header.scss
  components/default/Navbar.vue
  components/pages/TabBox.vue
  components/pages/UserHeader.vue
  layouts/default.vue
  pages/pages/_user.vue
Labels: enhancement

#68 アイキャッチ画像をコンポーネントにした
  components/user/Sidebar.vue
  components/user/storages/form/EmptyImage.vue
  components/user/storages/form/EyeCatchImageDisplay.vue
  components/user/storages/form/PreviewImage.vue
  pages/users/settings/index.vue
  pages/users/settings/password.vue
  pages/users/storages/create.vue
  pages/users/storages/edit.vue
  readme.md
  router.js
Labels: design, enhancement

#73 サイドバーのレスポンシブ対応
  assets/sass/app.scss
  assets/sass/user/_user_navbar.scss
  components/user/Sidebar.vue
  components/user/UserNavbar.vue
  layouts/user.vue
  pages/users/storages/create.vue
  pages/users/storages/edit.vue
Labels: design

#76 #58 Formのパーツをコンポーネント化した
  components/user/storages/form/FormDescription.vue
  components/user/storages/form/FormLongComment.vue
  components/user/storages/form/FormTitle.vue
  components/user/storages/form/FormWebAddress.vue
  mixins/form.js
  nuxt.config.js
  package-lock.json
  package.json
  pages/users/storages/create.vue
  pages/users/storages/edit.vue
  plugins/vuelidate.js
Labels: enhancement

#77 プロフィール一覧の削除と作品ファイルのacceptの追加
  pages/users/lists/profiles.vue
  pages/users/storages/create.vue
  pages/users/storages/edit.vue
  readme.md
  router.js
Labels: enhancement
